language: cpp
# sudo: required
# compiler:
#   - gcc
#   - clang
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - cmake
      - libsdl1.2-dev
      - liblua5.1-0-dev
      - libtolua++5.1-dev
      - libtolua-dev
      - zlib1g-dev
      - libpng12-dev
before_script:
  - "if [ $TRAVIS_OS_NAME == osx ]; then brew install lua51 sdl; \
         git clone https://github.com/LuaDist/toluapp.git; \
         cd toluapp; mkdir build;
           cd build; cmake ..; make; \
	     export CMAKEARGS=\"-DTOLUA++_INCLUDE_DIR=$(pwd)/../include/ -DTOLUA++_LIBRARY=$(pwd)/libtoluapp.dylib -DTOLUA++_APP=$(pwd)/toluapp\";
           cd ..;
         cd ..;
    fi"
  - mkdir build
  - cd build
  - cmake $CMAKEARGS ..
script: make
