shallow_clone: true
before_build:
  - mkdir build
  - cd build
  - appveyor DownloadFile https://github.com/Wargus/stratagus/releases/download/2015-30-11/dependencies.zip
  - 7z x dependencies.zip
  - cmake -G "Visual Studio 14 2015" -DCMAKE_PREFIX_PATH="%cd%\\dependencies" ..
  - cd ..
